### PR TITLE
add README.md

### PR DESCRIPTION
**Pull request by MartinDelille**
Hi,

I was looking at your project and since you didn't have README.md I decided to write it down.

Tell me if it is usefull!

### CODE REVIEW

**Comment by piscue** [comment]
no maintainer or reviewer?

**Comment by MartinDelille** [comment]
If you look at the [network view](https://github.com/notahat/midi_patchbay/network) you'll see that @ckd version is much more actively developed.

**Comment by danomatika** [comment]
@MartinDelille This has been integrated into PR #4.

@piscue Version 1.0.4 test build [here](http://docs.danomatika.com/releases/midipatchbay/)

**Comment by notahat** [comment]
This change is now on master.

**Pull request closed without merging**
